version: '3.8'

x-restart: &restart
  restart: on-failure

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.python
    <<: *restart
    networks:
      backend:
        ipv4_address: 172.20.0.5
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
    depends_on:
      - db

  db:
    image: mysql:8
    <<: *restart
    networks:
      backend:
        ipv4_address: 172.20.0.10
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST=%

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24